font_family JetBrainsMono Nerd Font
font_size 13.0
disable_ligatures always

cursor_blink_interval 0
mouse_hide_wait 3.0
input_delay 0
enable_audio_bell no

remember_window_size no
initial_window_width 120c
initial_window_height 35c
window_padding_width 2
hide_window_decorations titlebar-and-corners
confirm_os_window_close 0

foreground #e6edf3
background #000000
background_opacity 0.75
selection_foreground #e6edf3
selection_background #264f78
#: black
color0 #2e3138
# color8 #767676
#: red
color1 #ff7b72
# color9 #f2201f
#: green
color2 #3fb950
# color10 #23fd00
#: yellow
color3 #d4b26c
# color11 #fffd00
#: blue
color4 #58a6ff
# color12 #1a8fff
#: magenta
color5 #bc8cff
# color13 #fd28ff
#: cyan
color6 #39c5cf
# color14 #14ffff
#: white
color7 #b1bac4
# color15 #ffffff

macos_option_as_alt yes
macos_quit_when_last_window_closed yes
macos_show_window_title_in window

map cmd+equal change_font_size current +1.0
map cmd+minus change_font_size current -1.0
map cmd+0 change_font_size current 0

map kitty_mod+space>h show_scrollback
map kitty_mod+space>g show_last_command_output

# kitty_mod ctrl+shift+space
# map kitty_mod>h show_scrollback

# map cmd+k send_text all Special text
# map cmd+k send_text all "printf '\033[2J\033[3J\033[1;1H'"
# map cmd+k send_text all \033[2J\033[3J\033[1;1H
# map cmd+k send_text all \x1b[2J\x1b[3J\x1b[H
# map cmd+k \033[2J\033[3J\033[1;1H

# kitty_mod ctrl+cmd+opt+shift
# map kitty_mod+p show_scrollback
# map kitty_mod+x scroll_to_prompt 1
# map kitty_mod+h show_scrollback
# map kitty_mod+f5 load_config_file
# map cmd+k remote_control printf '\033[2J\033[3J\033[1;1H'
# map cmd+k clear_terminal to_cursor_scroll active
# map cmd+k clear_terminal clear active
# map cmd+k clear_terminal scrollback active
# map cmd+k clear_terminal to_cursor_scroll active
# map cmd+k combine : clear_terminal to_cursor_scroll active : clear_terminal clear active
# map cmd+k combine : clear_terminal scrollback active : send_text normal \x0c
# map cmd+k combine : clear_terminal scrollback active : send_text normal,application \x0c
# map kitty_mod+enter new_window
# map cmd+enter new_window
# map cmd+enter new_os_window_with_cwd
