set -g default-terminal "xterm-256color"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind R source-file ~/.tmux.conf \; display '~ Reloaded tmux config!'

setw -g mouse on
setw -g automatic-rename on
set-window-option -g mode-keys vi

set -g escape-time 0
set -g repeat-time 200

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r M-k resize-pane -U 1
bind -r M-j resize-pane -D 1
bind -r M-l resize-pane -L 1
bind -r M-h resize-pane -R 1

bind -r a last-window

# Change new panes in the same working directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g clock-mode-style 12
set-window-option -g clock-mode-colour colour69

# Statusline
set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=colour237,bg=colour114"
set -g status-right-style "none"
set -g pane-active-border-style "fg=colour114"
set -g status-style "none,bg=colour237"
set -g message-style "fg=colour237,bg=colour114"
set -g pane-border-style "fg=colour236"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "underscore,fg=colour114,bg=colour237"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=colour114,bg=colour237"
set -g status-left "#[fg=colour237,bg=colour114] [#S] #[fg=colour114,bg=colour237,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour236,bg=colour237,nobold,nounderscore,noitalics]#[fg=colour114,bg=colour236] #H #[fg=colour114,bg=colour236,nobold,nounderscore,noitalics]#[fg=colour237,bg=colour114] %l:%M%p %b-%d-%Y "
setw -g window-status-format "#[fg=colour237,bg=colour237,nobold,nounderscore,noitalics]#[default] #I:#W#F #[fg=colour237,bg=colour237,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=colour237,bg=colour114,nobold,nounderscore,noitalics]#[fg=colour237,bg=colour114] #I:#W#F #[fg=colour114,bg=colour237,nobold,nounderscore,noitalics]"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'

run '~/.tmux/plugins/tpm/tpm'

