#!/usr/bin/env bash

set -x

if command -v pyenv &>/dev/null && command -v pip &>/dev/null; then
    pip install -U \
        aiohttp \
        black \
        debugpy \
        matplotlib \
        mypy \
        numpy \
        pandas \
        pip \
        pylint \
        pytest \
        pytest-xdist \
        pyyaml \
        requests \
        ruff \
        tabulate \
        websockets

    pip install -U --user pipenv
fi
