#!/usr/bin/env bash

set -x

if command -v pyenv &>/dev/null && command -v pip &>/dev/null; then
	pip install -U \
		black \
		debugpy \
		matplotlib \
		mypy \
		numpy \
		pandas \
		pip \
		pipenv \
		pylint \
		pytest \
		pytest-xdist \
		pyyaml \
		requests \
		tabulate
fi
