set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

unbind-key C-b
set-option -g prefix C-Space

bind-key R source-file ~/.tmux.conf \; display '~ Reloaded tmux config!'

set-option -g automatic-rename-format "#{b:pane_current_path}"
set-option -g clock-mode-colour colour69
set-option -g clock-mode-style 12
set-option -g escape-time 0
set-option -g focus-events on
set-option -g history-limit 10000
set-option -g mode-keys vi
set-option -g mouse on
set-option -g repeat-time 200

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'

bind-key s choose-tree -Zs -O name
bind-key K clear-history

bind-key c new-window -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -hc "#{pane_current_path}"

bind-key -r Space last-window
bind-key -r M-H swap-window -t -1\; select-window -t -1
bind-key -r M-L swap-window -t +1\; select-window -t +1

bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

bind-key C-h select-pane -L \; resize-pane -Z
bind-key C-j select-pane -D \; resize-pane -Z
bind-key C-k select-pane -U \; resize-pane -Z
bind-key C-l select-pane -R \; resize-pane -Z

bind-key -r M-h resize-pane -L 5
bind-key -r M-j resize-pane -D 5
bind-key -r M-k resize-pane -U 5
bind-key -r M-l resize-pane -R 5

bind-key -r M-Left  resize-pane -L 1
bind-key -r M-Down  resize-pane -D 1
bind-key -r M-Up    resize-pane -U 1
bind-key -r M-Right resize-pane -R 1

bind-key W move-window -r
bind-key M-M choose-tree "join-pane -ht %%"
bind-key M-m command-prompt -T window-target "move-window -bt '%%'; move-window -r"
bind-key M-c command-prompt -T window-target "new-window -bt '%%'; move-window -r"

bind-key C-a list-panes -a -F "#{session_name} (#{window_name}): #{pane_current_path}"
bind-key P capture-pane
bind-key M-P command-prompt -p 'Save to file:' -I '~/tmux.history' 'capture-pane -S -; save-buffer %1; delete-buffer'
bind-key M-0 switch-client  -t config

# Statusline
set-option -g status "on"
set-option -g status-justify "left"
set-option -g status-style "none,bg=colour237"
set-option -g status-left-style "none"
set-option -g status-right-style "none"
set-option -g status-left-length "100"
set-option -g status-right-length "100"
set-option -g status-left "#[bold,fg=colour237,bg=colour114] #S #[fg=colour114,bg=colour237] "
set-option -g status-right "#[fg=colour114,bg=colour237] #H#[fg=colour114,bg=colour236,nobold,nounderscore,noitalics] #[fg=colour237,bg=colour114] #(TZ=UTC date -u '+%%H:%%M %%Z %%b-%%d-%%Y') "
set-option -wg window-status-separator " "
set-option -wg window-status-style "none,fg=colour114,bg=colour237"
set-option -wg window-status-activity-style "underscore,fg=colour114,bg=colour237"
set-option -wg window-status-format "#[default] #I:#W#F "
set-option -wg window-status-current-format "#[fg=colour237,bg=colour114] #I:#W#F "
set-option -g message-style "fg=colour237,bg=colour114"
set-option -g message-command-style "fg=colour237,bg=colour114"
set-option -g pane-active-border-style "fg=colour114"
set-option -g pane-border-style "fg=colour236"

set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @resurrect-strategy-nvim 'session'

run '~/.tmux/plugins/tpm/tpm'
