#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
  window_zoom_persist 'off' \
  window_shadow 'float' \
  normal_window_opacity '1.0' \
  window_animation_duration '0.0' \
  split_ratio '0.5' \
  mouse_modifier 'alt' \
  mouse_action1 'move' \
  mouse_action2 'resize' \
  mouse_drop_action 'stack' \
  layout 'bsp' \
  top_padding '10' \
  bottom_padding '10' \
  left_padding '10' \
  right_padding '10' \
  window_gap '10'

yabai -m rule --add \
  app!="^(Alacritty|kitty|Google Chrome|Firefox)$" \
  manage=off

yabai -m rule --add \
  app="Google Chrome" \
  title="^(Bitwarden.*|Task Manager)$" \
  manage=off

yabai -m rule --add \
  app="Firefox" \
  title="Library|^Extension:" \
  manage=off

yabai -m signal --add \
  event=window_focused \
  action="yabai -m window $YABAI_WINDOW_ID --sub-layer normal"

yabai -m signal --add \
  event=window_minimized \
  action="yabai -m query --windows --window \$YABAI_WINDOW_ID | \
            jq -e '.\"is-floating\" == false' && \
            yabai -m window \$YABAI_WINDOW_ID --toggle float"
